import type { DatasetKey } from "../types/domain";
import type { DatasetMappings } from "../types/mapping";

/** Ordered semantic fields per dataset — used for mapping UI and generated templates. */
export const SEMANTIC_FIELDS: Record<DatasetKey, string[]> = {
  demandOutlook: [
    "month",
    "customer",
    "market",
    "ceManager",
    "packagingType",
    "plant",
    "region",
    "sku",
    "productFamily",
    "budgetValue",
    "budgetVolume",
    "priorForecastValue",
    "priorForecastVolume",
    "currentForecastValue",
    "currentForecastVolume",
    "actualValue",
    "actualVolume",
    "driver",
    "confidence",
    "owner",
    "reconfirmDate",
    "notes",
  ],
  budget: ["month", "customer", "market", "budgetValue", "budgetVolume"],
  forecastPerformance: [
    "forecastCycle",
    "month",
    "customer",
    "skuGroup",
    "segment",
    "forecast",
    "actual",
    "fca",
    "bias",
    "volatility",
  ],
  actuals: ["month", "customer", "sku", "actualValue", "actualVolume"],
  capacity: [
    "month",
    "format",
    "plant",
    "packagingType",
    "demand",
    "ratedCapacity",
    "effectiveCapacity",
    "utilization",
    "affectedCustomers",
    "revenueAtRisk",
    "volumeAtRisk",
    "mitigation",
    "owner",
    "incrementalCapacityNote",
  ],
  npdReadiness: [
    "customer",
    "project",
    "firstShipmentMonth",
    "monthlyVolume",
    "packagingType",
    "plant",
    "confidence",
    "capacityReadiness",
    "rmPackagingReadiness",
    "qaArtworkReadiness",
    "commercialReadiness",
    "riskFlag",
    "owner",
    "dueDate",
  ],
  issues: [
    "id",
    "title",
    "kind",
    "valueImpact",
    "volumeImpact",
    "confidence",
    "supplyImplication",
    "decisionRequired",
    "owner",
    "dueDate",
    "status",
    "needsSupplyReview",
    "needsExecEscalation",
  ],
  actions: [
    "id",
    "category",
    "description",
    "owner",
    "dueDate",
    "status",
    "impact",
    "dependency",
    "decisionForum",
    "nextReviewDate",
    "notes",
  ],
  demandExceptions: [
    "id",
    "type",
    "customer",
    "product",
    "month",
    "impactValue",
    "impactVolume",
    "confidence",
    "rootCause",
    "decisionRequired",
    "owner",
    "dueDate",
    "status",
    "severity",
  ],
};

/** Suggested default Excel headers when downloading templates (editable in-app). */
export const DEFAULT_COLUMN_HINTS: DatasetMappings = {
  demandOutlook: {
    month: "Month",
    customer: "Customer",
    market: "Market",
    ceManager: "CE Manager",
    packagingType: "Packaging Type",
    plant: "Plant",
    region: "Region",
    sku: "SKU",
    productFamily: "Product Family",
    budgetValue: "Budget Value",
    budgetVolume: "Budget Volume",
    priorForecastValue: "Prior Forecast Value",
    priorForecastVolume: "Prior Forecast Volume",
    currentForecastValue: "Current Forecast Value",
    currentForecastVolume: "Current Forecast Volume",
    actualValue: "Actual Value",
    actualVolume: "Actual Volume",
    driver: "Driver",
    confidence: "Confidence",
    owner: "Owner",
    reconfirmDate: "Reconfirm Date",
    notes: "Notes",
  },
  budget: {
    month: "Month",
    customer: "Customer",
    market: "Market",
    budgetValue: "Budget Value",
    budgetVolume: "Budget Volume",
  },
  forecastPerformance: {
    forecastCycle: "Forecast Cycle",
    month: "Month",
    customer: "Customer",
    skuGroup: "SKU Group",
    segment: "Segment",
    forecast: "Forecast",
    actual: "Actual",
    fca: "FCA",
    bias: "Bias",
    volatility: "Volatility",
  },
  actuals: {
    month: "Month",
    customer: "Customer",
    sku: "SKU",
    actualValue: "Actual Value",
    actualVolume: "Actual Volume",
  },
  capacity: {
    month: "Month",
    format: "Format",
    plant: "Plant",
    packagingType: "Packaging Type",
    demand: "Demand",
    ratedCapacity: "Rated Capacity",
    effectiveCapacity: "Effective Capacity",
    utilization: "Utilization",
    affectedCustomers: "Affected Customers",
    revenueAtRisk: "Revenue At Risk",
    volumeAtRisk: "Volume At Risk",
    mitigation: "Mitigation",
    owner: "Owner",
    incrementalCapacityNote: "Incremental Capacity Note",
  },
  npdReadiness: {
    customer: "Customer",
    project: "Project",
    firstShipmentMonth: "First Shipment Month",
    monthlyVolume: "Monthly Volume",
    packagingType: "Packaging Type",
    plant: "Plant",
    confidence: "Confidence",
    capacityReadiness: "Capacity Readiness",
    rmPackagingReadiness: "RM Packaging Readiness",
    qaArtworkReadiness: "QA Artwork Readiness",
    commercialReadiness: "Commercial Readiness",
    riskFlag: "Risk Flag",
    owner: "Owner",
    dueDate: "Due Date",
  },
  issues: {
    id: "Issue ID",
    title: "Issue",
    kind: "Type",
    valueImpact: "Value Impact",
    volumeImpact: "Volume Impact",
    confidence: "Confidence",
    supplyImplication: "Supply Implication",
    decisionRequired: "Decision Required",
    owner: "Owner",
    dueDate: "Due Date",
    status: "Status",
    needsSupplyReview: "Needs Supply Review",
    needsExecEscalation: "Needs Exec Escalation",
  },
  actions: {
    id: "Action ID",
    category: "Category",
    description: "Description",
    owner: "Owner",
    dueDate: "Due Date",
    status: "Status",
    impact: "Impact",
    dependency: "Dependency",
    decisionForum: "Decision Forum",
    nextReviewDate: "Next Review Date",
    notes: "Notes",
  },
  demandExceptions: {
    id: "Exception ID",
    type: "Type",
    customer: "Customer",
    product: "Product",
    month: "Month",
    impactValue: "Impact Value",
    impactVolume: "Impact Volume",
    confidence: "Confidence",
    rootCause: "Root Cause",
    decisionRequired: "Decision Required",
    owner: "Owner",
    dueDate: "Due Date",
    status: "Status",
    severity: "Severity",
  },
};
